l=[1,2,3,1]
print(len(l))
print(l.count(1))
print(l.index(1))
l.append(5)
print(l)
l.insert(3,'sakshi')
print(l)
l2=["saksh","doshi"]
l.extend(l2)
print(l)
l.remove(1)
print(l)
print(l.pop())
print(l)
l.clear()
print(l)
l1=[1,6,8,3,4,7,9,15]
l1.sort()
print(l1)
l1.reverse()
print(l1)
print(max(l1))
print(min(l1))


s='the quick brown fox jumps over lazy dog'
print(list(s))
s1=list(s)
s1.sort()
print(s1)
print(set(s1))
s2=set(s1)
s3=list(s2)
s3.sort()
print(s3)
print(''.join(s3))